### PR TITLE
fix: phpstan issues

### LINKED ISSUE #315: Drupal 10, PHP 8.2 and PHPStan issues
The work on https://github.com/localgovdrupal/localgov_project/pull/131 has highlighted some PHP 8.2 and PHPStan issues which need fixing.

```
 ------ --------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/modules/localgov_directories_location/src/ProximitySearchSetup.php  
 ------ --------------------------------------------------------------------------------------------------------- 
  75     Variable $index_datasrc in empty() always exists and is not falsy.                                       
 ------ --------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/modules/localgov_directories_venue/tests/src/Kernel/ViewUpgradeForProximitySearchTest.php  
 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  42     Variable $display_for_proximity_search in empty() always exists and is not falsy.                                               
 ------ -------------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------ 
  Line   modules/contrib/localgov_directories/src/ConfigurationHelper.php  
 ------ ------------------------------------------------------------------ 
  218    Variable $config_src in empty() always exists and is not falsy.   
 ------ ------------------------------------------------------------------ 

 ------ ---------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/src/Form/LocalgovDirectoriesFacetsForm.php                                                   
 ------ ---------------------------------------------------------------------------------------------------------------------------------- 
  53     Method Drupal\localgov_directories\Form\LocalgovDirectoriesFacetsForm::save() should return int but return statement is missing.  
 ------ ---------------------------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/src/Form/LocalgovDirectoriesFacetsTypeForm.php                                                   
 ------ -------------------------------------------------------------------------------------------------------------------------------------- 
  95     Variable $message might not be defined.                                                                                               
  97     Method Drupal\localgov_directories\Form\LocalgovDirectoriesFacetsTypeForm::save() should return int but return statement is missing.  
 ------ -------------------------------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/tests/src/Functional/ResetFacetFilterTest.php                                              
 ------ -------------------------------------------------------------------------------------------------------------------------------- 
  74     Access to an undefined property Drupal\Tests\localgov_directories\Functional\ResetFacetFilterTest::$directory_channel_node_id.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                            
  103    Access to an undefined property Drupal\Tests\localgov_directories\Functional\ResetFacetFilterTest::$directory_channel_node_id.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                            
  132    Access to an undefined property Drupal\Tests\localgov_directories\Functional\ResetFacetFilterTest::$directory_channel_node_id.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                            
 ------ -------------------------------------------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/tests/src/Kernel/EntityReferenceChannelsSelectionTest.php                                    
 ------ ---------------------------------------------------------------------------------------------------------------------------------- 
  82     Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  87     Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$page_type.        
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  97     Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$other_type.       
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  113    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$page_type.        
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  114    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$page_type.        
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  119    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  120    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  125    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  126    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$other_type.       
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  131    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  132    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  137    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$other_type.       
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  138    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$other_type.       
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  141    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  144    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
  145    Access to an undefined property Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelectionTest::$directory_nodes.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                              
 ------ ---------------------------------------------------------------------------------------------------------------------------------- 
```

### PR DESCRIPTION
**Pull request by millnut**
Fix issues reported in https://github.com/localgovdrupal/localgov_directories/issues/315

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]

**Comment by finnlewis** [comment]
woops - approved the wrong one, sorry, too many tabs!

File: src/ConfigurationHelper.php [hunk 1]
```diff
@@ -215,7 +215,7 @@ public function insertedTitleSortField(FieldConfigInterface $field): void {
    */
   public function importConfigEntity(string $entity_type, string $config_path, string $config_filename): bool {
     $config_src = new ConfigFileStorage($config_path);
-    if (empty($config_src)) {
+    if (!$config_src instanceof ConfigFileStorage) {
```
Comment (Adnan-cds) [inline src/ConfigurationHelper.php:218]: It's unfortunate we are having to go through all these gymnastics simply because of a bug in PHPStan.  This one, for example, reduces the readability of the code by a tiny amount :(

**Review by Adnan-cds — APPROVED** [review]
Thanks.
